### ISSUE TITLE
Domain name?

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#20]
dc-code.com is available, or dccodebrowser.com or something

**Comment by waldoj** [comment]
dccode.org is available.

**Comment by waldoj** [comment]
dclaws.org is also available.

**Comment by tmcw** [comment]
so, like... dccode.com is lexisnexis. is it okay to grab such a close parallel?

**Comment by waldoj** [comment]
It's only problematic if a) they have a trademark on "DC Code" (or "dccode.com") and/or b) there is a "reasonable likelihood of confusion" between dccode.com and dccode.org. I cannot find any reference to "dccode.com" _anywhere_, making it pretty tough to argue that anybody could possibly confuse dccode.org with LexisNexis's nonexistent site of a similar name. (The domain doesn't even load a copy of the DC Code.) If I were in your shoes, I'd be totally comfortable with this, but I am neither a lawyer nor your lawyer. :)

**Comment by konklone** [comment]
I'd grab dccode.org right now, before someone notices this thread. It's a great comparator to the West one: dccode.com is the commercial one, dccode.org is the upstart community effort. I love it.

**Comment by tmcw** [comment]
cool, grabbed it.

**Comment by JoshData** [comment]
Trademark it and then sue Lexis. (Joking, or am I?)

**Comment by konklone** [comment]
Looks done!
