### ISSUE TITLE
browse by section rather than subsection

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#22]
Something that would be super-useful to @vzvenyach - the ability to pull up sections rather than subsections!

**Comment by tmcw** [comment]
Appears not to be an issue? Is 1-100.1 'section 100.1'?

**Comment by vdavez** [comment]
Sort of. The number before the hyphen refers to the title of the Code. But the issue I mentioned is browsing by chapters, because sometimes, acts are codified as a single chapter or a subchapter of a title)

**Comment by konklone** [comment]
That makes sense. So it'd potentially be adding a nav layer between title and section, or aggregating the section layer into chapters that unfold into section lists or something.

The question @tmcw was asking was to verify my own hunch: in the hierarchy of the DC Code, is `1-100` a sibling to `1-611.01`? I believe the answer is yes - that these are both at the level of "section". `1-100` is a section inside of Title 1, Chapter 1, and `1-611.01` is a section inside of Title 1, Chapter 6.

**Comment by vdavez** [comment]
Correct
