### ISSUE TITLE
Title 4?

### ISSUE THREAD

**Issue by vdavez** [openlawdc/browser#36]
Not really sure if I'm using this right yet, but I'm not seeing Title 4. That said, everything else that I see, I like!

**Comment by schmod** [comment]
This really belongs in the dc-decoded project, but yeah, something's definitely wrong here.  

Title 4 does indeed exist, and I'm not quite sure how none of us noticed...

**Comment by schmod** [comment]
Should be fixed as of 9dd21c22e1a108b573aba24b8919264c5ac3b135

Feel free to re-open if anything else seems to be missing.

**Comment by schmod** [comment]
My bad.  9dd21c22e1a108b573aba24b8919264c5ac3b135 should have _actually_ fixed things.
