### ISSUE TITLE
Cross-reference detection in JS

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#4]

**Comment by konklone** [comment]
If it's any help, https://github.com/unitedstates/citation/issues/22 is one of my plans for the DC Code Hackathon.

**Comment by konklone** [comment]
Can you point to an example of the kind of cross-reference you want to catch? There are the complicated ones in the Credits sections, but I think you mean cross-references from one section of the current DC Code to another in the current DC Code?

And since you're also doing this in JS - what would be the most useful interface to provide cross reference detection/linking? I've been considering whether/how to add an option to [my citation library](https://github.com/unitedstates/citation) that returns the string transformed with matched citations marked up. Maybe adding a `replace` callback option, like:

``` javascript
Citation.find("pursuant to 5 U.S.C. 552(a)(1)(E) and", {
  types: ["usc"],
  replace: function(match) {
    var url = "http://www.law.cornell.edu/uscode/text/" + match.usc.title + "/" + match.usc.section;
    return "<a href=\"" + url + "\">" + match.match + "</a>";
  }
});
```

Which would yield a JSON object containing the usual array of match results, plus the transformed string:

``` json
{
  "results": [{
    "match": "5 U.S.C. 552(a)(1)(E)",
    "type": "usc",
    "index": "12",
    "usc": {
      "title": "5",
      "section": "552",
      "subsections": ["a", "1", "E"],
      "id": "usc/5/552/a/1/E",
      "section_id": "usc/5/552"
    }
  }],
  "replaced": "pursuant to <a href=\"http://www.law.cornell.edu/uscode/text/5/552\">5 U.S.C. 552(a)(1)(E)</a> and"
}
```

Is this an approach that would make using a third-party library like [unitedstates/citation](https://github.com/unitedstates/citation) make sense for this project?

**Comment by tmcw** [comment]
> Can you point to an example of the kind of cross-reference you want to catch? There are the complicated ones in the Credits sections, but I think you mean cross-references from one section of the current DC Code to another in the current DC Code?

At first, it'd be cool to just catch references in the text & sections of laws. For instance, 3-202, which references 32-701. The citation module looks perfect for this.

**Comment by konklone** [comment]
I've got cross-reference detection working for the DC Code, and added support for passing "context" to a citation parser that allows it to detect inline stuff ([example](https://github.com/unitedstates/citation#context-aware-citation-detection)).

The [DC Code parser](https://github.com/unitedstates/citation/blob/master/citations/dc_code.js) detects both absolute and relative cites. The kinds I detect, documented in comments above each pattern, are all sourced from official documents - the [test cases](https://github.com/unitedstates/citation/blob/master/test/dc_code.js) for dc_code have links to the sources where possible. I took examples from the DC Code, DC legislation, proposed DC regulations from the Register, and final DC regulations from the register. I also looked over an example Mayoral Order, and verified that it used one of the formats I already tested.

I by no means did an exhaustive search, so it'll be interesting to see this used in the wild in a real document viewer, so we can see any examples that get missed.

I haven't tackled supporting a "replace" option that would let you provide a callback to actually mark up and autolink the supplied text - is this something you'd like, or is just detecting the cites enough?

**Comment by konklone** [comment]
OK, there's a `replace` callback option now. It works as described above, except the key for the transformed text is just `text`.

I just ran this JavaScript:

``` javascript
text = "...of the term \"independent agency\" as provided in § 1-603.01(13).\n\n(b) In addition to the duties required under § 3-101.01, the Commission shall perform...";

Citation.find(text, {
  types: "dc_code",
  context: {source: "dc_code"},
  replace: function(cite) {
    var url = "http://dccode.org/browse/current/" + cite.dc_code.title + "-" + cite.dc_code.section;
    return "<a href=\"" + url + "\">" + cite.match + "</a>";
  }
})
```

And got this in response:

``` json
{
  "citations": [
    {
      "type": "dc_code",
      "match": "§ 1-603.01(13)",
      "dc_code": {
        "title": "1",
        "section": "603.01",
        "subsections": ["13"],
        "id": "dc-code/1/603.01/13",
        "section_id": "dc-code/1/603.01"
      }
    },
    {
      "type": "dc_code",
      "match": "§ 3-101.01",
      "dc_code": {
        "title": "3",
        "section": "101.01",
        "subsections": [],
        "id": "dc-code/3/101.01",
        "section_id": "dc-code/3/101.01"
      }
    }
  ],
  "text": "...of the term \"independent agency\" as provided in <a href=\"http://dccode.org/browse/current/1-603.01\">§ 1-603.01(13)</a>.\n\n(b) In addition to the duties required under <a href=\"http://dccode.org/browse/current/3-101.01\">§ 3-101.01</a>, the Commission shall perform..."
}
```

In the original call to `Citation.find`, the `types` value of "dc_code" (it can be an array) is there to limit detection to DC Code cites. 

The `context.source` value of "dc_code" is needed to make the parser comfortable with detecting inline citations, that don't explicitly have the words "DC Official Code" before them, as they do in other non-Code documents. 

The `replace` callback gets called with exactly the same data structure that ends up accumulated in the returned `citations` array.

I still have some [extra tests/docs tasks](https://github.com/unitedstates/citation/issues/26) to do around this, but I think it's definitely in a usable state for Sunday.

**Comment by konklone** [comment]
Thinking on it more, I might also add support for taking a [Mustache.js](https://github.com/janl/mustache.js/) template string as a value for `replace`. A callback would give more flexibility, but a Mustache.js template would be something that the HTTP and CLI interfaces could reasonably accept. I don't think that's getting done for Sunday unless it needs to, though.

**Comment by MrChadRobinson** [comment]
Pete and I were looking in the code browser and discovered that the credits at the bottom included US Public Law citations as well at the DC Code citations within the text. Pete would want to be able to run public law number searches through govtrack.us so we can link back to that text in the credits.

**Comment by konklone** [comment]
For the record, the pattern for GPO's official Public Law links is:

``` text
http://www.gpo.gov/fdsys/pkg/PLAW-{{ congress }}publ{{ number }}/pdf/PLAW-{{ congress }}publ{{ number }}.pdf
```

Change the first "pdf" to "html" and the second "pdf" to "htm" to get the plaintext version (the only html is a `<pre>` tag).

Examples:
http://www.gpo.gov/fdsys/pkg/PLAW-113publ1/pdf/PLAW-113publ1.pdf
http://www.gpo.gov/fdsys/pkg/PLAW-113publ1/html/PLAW-113publ1.htm

**Comment by konklone** [comment]
Either way, when you have Public Law cite URLs done, you can close this ticket - further cite types we can track in individual tickets, now that the system is in place.

**Comment by konklone** [comment]
Just saw your pull request - awesome! Merged it, closing this ticket.
