### ISSUE TITLE
Title/Section overflow scrollbars cropped on win32

### ISSUE THREAD

**Issue by schmod** [openlawdc/browser#42]
![overflow](https://f.cloud.github.com/assets/1102667/381283/46d7248e-a5dc-11e2-818c-bb372907084b.jpeg)

**Comment by tmcw** [comment]
@schmod the touchups I posted sacrifice the fixed-position titles in favor of scrolling titles and honest scrollbars. Please check - this should be fixed.

**Comment by schmod** [comment]
Works, but not sure I love the compromise.

**Comment by tmcw** [comment]
Yep, if anyone wants to reintroduce the previous behavior but make this work and make scrollIntoView work, plz do. Will close here though.
