### ISSUE TITLE
Figure out links to DC Law numbers

### ISSUE THREAD

**Issue by konklone** [openlawdc/browser#45]
They exist in places (examples in the Credits section of [3-102](http://dccode.org/code-browser/#/3/3-102). 

However, I don't know how possible it is to construct a permalink that references a DC Law (slip law) number. LIMS has permalinks by bill (act) numbers, but I can't find anything for slip law numbers.

@vzvenyach, do you have any insight here?

**Comment by vdavez** [comment]
I will double check.

**Comment by vdavez** [comment]
Have a potentially janky solution. Would a classification table that compares a bill # to a law # get you there?

**Comment by konklone** [comment]
We could definitely use that, yeah!

**Comment by vdavez** [comment]
So. I have a CSV that goes back to Council Period 15. How do I get that to you?

**Comment by konklone** [comment]
Immediate term, you can upload it somewhere and provide a link, or you can make a little repo for it here and commit it there. You can even just email it to me at konklone@gmail.com if you want, which will cause me to do one of the previous two things myself. :)

**Comment by konklone** [comment]
Thanks to @aturoff and @vzvenyach, this is done in https://github.com/openlawdc/browser/commit/fd8fe9984fa0786bc30d1a6df1654cb9edec3b6f!

This did involve dropping a generated JSON file into the global namespace, as "dc_laws". It's in [dc_laws.js](https://github.com/openlawdc/browser/blob/gh-pages/js/dc_laws.js). Ideally this would be stored as a JSON file instead of a JS file and loaded dynamically, I just didn't want to figure out the best way to load it in asynchronously but reliably have it available at cite-lookup time. Refactoring on that front, or suggestions for how I can do it, are very welcome!
