### ISSUE TITLE
DCR Links

### ISSUE THREAD

**Issue by konklone** [openlawdc/browser#46]
These appear all over the place - see the Credits of [3-102](http://dccode.org/code-browser/#/3/3-102) for an example, e.g. 54 DCR 8014.

It's not clear to me what this references. If it's the DC Register, is 54 the volume number? If so, [volume 54](http://www.dcregs.dc.gov/Gateway/IssueHome.aspx?IssueId=265) only has 254 pages, and the number 8014 doesn't seem to mean much to it.

Is it a DCMR citation? I can't find a title 54 of the DCMR, they only [go up to 31](http://www.dcregs.dc.gov/Search/DCMRSearchByTitle.aspx).

**Comment by konklone** [comment]
@vzvenyach, hate to keep summoning you, but would love to know if you have any insight on this one too.

**Comment by vdavez** [comment]
54 refers to the annual volume. The number 8014 refers to the page in the volume. Part of your problem is that the DCRegs site doesn't have Register pages before 10/2/09. So, the low end of the range is 56 DCR 7763.

**Comment by konklone** [comment]
Oh, you're right - that volume 54 is just the Cover and TOC. OK, I'll probably just link directly to the PDF for volumes  57 and up.

**Comment by konklone** [comment]
So there is no single PDF per-volume, as it turns out. And to link to the right issue would take creating a map of issue number to page range, so for the time being, I've linked DCR links (with volume 57 and above) to their landing page on the DC Register homepage. See the Credits of [3-101](http://dccode.org/browser/#/3/3-101) for an example.
