### ISSUE TITLE
General purpose modal for text/link hovers

### ISSUE THREAD

**Issue by konklone** [openlawdc/browser#49]
Anyone know a good little visual overlay plugin, or simple CSS, to let us use some links to generate hovers?

I'm looking at how SD's VA Code does hovers for glossary terms ([examples](http://vacode.com/8.1A-201/)).

I'd like to use it on older Statutes cites to let the click-er know that material that old isn't online in a digital form (and maybe a link to go complain?). But I suspect we could integrate the modal into the project in a general-purpose way, where we can just supply it with HTML to display.

**Comment by waldoj** [comment]
I do that with a jQuery plugin called [qTip](https://github.com/craga89/qtip2).

**Comment by tmcw** [comment]
We've also got a port of bootstrap's tooltips to d3 in the d3-bootstrap project. Of course, step 1 is filtering out references we want tooltips for and setting the data.

**Comment by konklone** [comment]
Is that [this](https://github.com/shawnbot/d3-bootstrap), @tmcw? If so, [this example](http://prag.ma/code/d3-bootstrap/examples/tooltip.html) looks good, I can work with that. (Never used D3, but it looks easy enough to get the tooltip assigned.)

**Comment by tmcw** [comment]
btw, if you're going to embark on one of the larger pushes, please do it in the `links` branch, which is becoming a very large refactor branch.

**Comment by konklone** [comment]
Had no idea. My only pushes tonight were self-contained in the cites
section. I won't work on this one until you've merged it in.

On Wed, Apr 17, 2013 at 10:25 PM, Tom MacWright notifications@github.comwrote:

> btw, if you're going to embark on one of the larger pushes, please do it
> in the links branch, which is becoming a very large refactor branch.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openlawdc/browser/issues/49#issuecomment-16550036
> .

## 

Developer | sunlightfoundation.com

**Comment by tmcw** [comment]
Yeah, I didn't really know either - thought it would be a quick feature branch but waterfalled into deeper refactoring. Should be done by the end of the week.

**Comment by tmcw** [comment]
Merged! Hack away (and note bugs)!

**Comment by konklone** [comment]
I ended up not using the modal plugin, and just using the natural tooltip you get by hovering over something with a `title` attribute. I added a dashed underline under non-linkable cites, and when you hover it tells you why it's not linked.

**Comment by konklone** [comment]
Oh yeah - it's in https://github.com/openlawdc/browser/commit/d91bbafd4410758c7b37f1a457f546a241b4d22e.
