### ISSUE TITLE
Googleability

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#50]
This is a big one, and probably means a bunch of changes.

Right now it doesn't look like google is trying to index the site.
- Links should be `<a>` elements, not spans.
- https://developers.google.com/webmasters/ajax-crawling/

**Comment by schmod** [comment]
Yeah, I noticed this too.  Facebook's parser also has trouble when you try
to share things.

On Wed, Apr 17, 2013 at 2:56 PM, Tom MacWright notifications@github.comwrote:

> This is a big one, and probably means a bunch of changes.
> 
> Right now it doesn't look like google is trying to index the site.
> - Links should be <a> elements, not spans.
> - ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openlawdc/browser/issues/50
> .

## 

Andrew Schmadel
schmod@gmail.com
