### ISSUE TITLE
lawUrlFor should probably use encodeURIFragment or whatnot

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#53]

**Comment by konklone** [comment]
Started this, but just noticed that the URL generation is too naive anyway. Looking at the Historical section for [1-123](http://dccode.org/browser/#/1/1-123), the citation detector catches a specific section cite of `Section 128 of Pub. L. 104-194`. I don't know of a way to link to a specific section of a US slip law, but it does mean that the URL should be generated by looking at the broken up parts of the cite, not using the match text. Fixing now.
