### ISSUE TITLE
remove google fonts dep

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#54]
this slows down the site when google fonts is slow / users are offline

**Comment by tmcw** [comment]
(by 'remove' I mean download and link fonts locally)

**Comment by konklone** [comment]
is that hard to do? don't you have to set headers and do fancy things to support oldIE or something?

**Comment by tmcw** [comment]
Older IEs just fall back to sans-serif/Helvetica/whatever - works pretty well on other gh-pages hosted projects (mapbox.com etc)
