### ISSUE TITLE
Cut off text at the start of a section

### ISSUE THREAD

**Issue by JoshData** [openlawdc/browser#57]
§ 23-542 is missing text at the start of the section: http://dccode.org/browser/#/23/23-542

**Comment by tmcw** [comment]
Present in the JSON source, so upstream in dc-decoded. -> https://github.com/openlawdc/dc-decoded/issues/19

**Comment by JoshData** [comment]
Ooops, sorry, I should have checked that and posted the issue in the right place. Thanks.
