### ISSUE TITLE
Update to new release of the code

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#65]
http://dccouncil.us/UnofficialDCCode

Doit!

**Comment by waldoj** [comment]
This is one of those rare occasions when plain text constitutes an improvement!

**Comment by tmcw** [comment]
Yep, saves us a step!

**Comment by tmcw** [comment]
(background is that the parser, https://github.com/openlawdc/dc-decoded already threw away all markup and converted to text - it will _probably_ work with minimal modifications on the new source)

**Comment by tmcw** [comment]
Happening in the `update` branch of dc-decoded, tracking with https://github.com/openlawdc/dc-decoded/issues?milestone=1&state=open
