### ISSUE TITLE
404 at 5-606..json

### ISSUE THREAD

**Issue by tmcw** [openlawdc/browser#7]

**Comment by waldoj** [comment]
To be clear, this is happening for _all_ requests for laws, not just `5-606.json`.

**Comment by tmcw** [comment]
Yep, the index & actual files have two periods in them. Fixing now.

**Comment by tmcw** [comment]
Fixed in https://github.com/openlawdc/dc-decoded/commit/8e762b9e487906dcb5a5ae84a0d0febeb53805d6 with the decoder. Need to work on a regex for headings that doesn't capture the `.` - the `.` is not a part of the identifier, right?

**Comment by waldoj** [comment]
That's right, the trailing dot is not part of the identifier.
