### ISSUE TITLE
403 response for individual law JSON files

### ISSUE THREAD

**Issue by waldoj** [openlawdc/browser#9]
e.g. http://dccodebrowser.s3-website-us-east-1.amazonaws.com/sections/6-101.05.json

**Comment by tmcw** [comment]
Will check in a few minutes, 4k/16k laws in and I think that one's queued up.

**Comment by waldoj** [comment]
Ah, got it—403 may mean 404 in this context.

**Comment by tmcw** [comment]
Rebuild of sections renamed that to http://dccodebrowser.s3-website-us-east-1.amazonaws.com/sections/6-10105.json - will look into whether this is going to cause any ambiguity. Fixed the request in https://github.com/openlawdc/code-browser/commit/6a7496a224e5b91c27023860cd7dac8c61d9e7cb

**Comment by waldoj** [comment]
Yes, that will cause ambiguity. I strongly recommend not taking that route to file naming.

**Comment by tmcw** [comment]
Cool, made ids more honest. Will push a new version this afternoon.
